// <auto-generated />
namespace FL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Changeddatetimetype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changeddatetimetype));
        
        string IMigrationMetadata.Id
        {
            get { return "201512202154435_Changed datetime type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
